config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'

  resources :events do
    # вложенный ресурс комментов
    resources :comments, only: [:create, :destroy]

    # вложенный ресурс подписок
    resources :subscriptions, only: [:create, :destroy]

    # Вложенные в ресурс события ресурсы фотографий
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/event.rb
# Модель события
class Event < ActiveRecord::Base
  # событие принадлежит юзеру
  belongs_to :user

  # у события много комментариев и подписок
  has_many :comments
  has_many :subscriptions

  # у события много фотографий
  has_many :photos

  # у события много подписчиков (объекты User), через таблицу subscriptions, по ключу user_id
  has_many :subscribers, through: :subscriptions, source: :user

  # юзера не может не быть
  validates :user, presence: true

  # заголовок должен быть, и не длиннее 255 букв
  validates :title, presence: true, length: {maximum: 255}

  # также у события должны быть место и время проведения
  validates :address, presence: true
  validates :datetime, presence: true

  # Метод, который возвращает всех, кто пойдет на событие:
  # всех подписавшихся и организатора
  def visitors
    (subscribers + [user]).uniq
  end
end

app/controllers/events_controller.rb
# Контроллер, управляющий событиями
class EventsController < ApplicationController
  # встроенный в девайз фильтр - посылает незалогиненного пользователя
  before_action :authenticate_user!, except: [:show, :index, :destroy]

  # задаем объект @event для экшена show
  before_action :set_event, only: [:show]

  # задаем объект @event от текущего юзера
  before_action :set_current_user_event, only: [:edit, :update, :destroy]


  before_action :pincode_guard, only: [:show]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
    # Болванка модели для формы добавления комментария
    @new_comment = @event.comments.build(params[:comment])

    # Болванка модели для формы подписки
    @new_subscription = @event.subscriptions.build(params[:subscription])

    # Болванка модели для формы добавления фотографии
    @new_photo = @event.photos.build(params[:photo])
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_path, notice: I18n.t('controllers.events.destroyed')
  end

  private
  def pincode_guard
    return if @event.pincode.blank?
    return if user_signed_in? && current_user == @event.user

    if params[:pincode].present? && @event.pincode == params[:pincode]
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    if cookies.permanent["events_#{@event.id}_pincode"] != @event.pincode
      flash.now[:alert] = 'Wrong pincode' if params[:pincode].present?
      render 'pincode_form'
    end
  end

  def set_current_user_event
    @event = current_user.events.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<%# Паршиал отображения инфы об отдельном событии %>
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">

    <%= content_tag 'div', '',
                    class: 'event-background',
                    style: "background-image: url(#{event_thumb(event)})"
    %>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3>
            <%# Для перевода времени в русский формат используем I18n %>
            <%# Формат при этом используется из гема russian %>
            <small><%= l event.datetime, format: :short %></small>
          </h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
        <div>
          <%# Выводим всех пользователей, которые придут на событие, выводя их аватарки %>
          <% event.visitors.each do |user| %>
              <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%# Паршиал отображения формы создания нового события %>
<%= form_for(@event) do |f| %>
    <%= render partial: 'partials/form_errors', locals: {model: @event} %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :datetime %>
      <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :pincode %>
      <%= f.text_field :pincode, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit 'Сохранить', class: 'btn btn-primary' %> или <%= link_to 'вернуться', :back %>
    </div>
<% end %>

app/views/events/edit.html.erb
<h1>Редактирование события</h1>

<div class="row">
  <div class="col-md-6 buffer-top">

    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<h1>События</h1>

<div class="buffer-both">
  <%= link_to 'Создать событие', new_event_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%# Рендерим сразу массив событий, каждый в паршиале 'events/event' %>
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1>Новое событие</h1>

<div class="row">
  <div class="col-md-6 buffer-top">

    <%= render 'form' %>
  </div>
</div>

app/views/events/pincode_form.html.erb
<h1>Доступ только по пин-коду</h1>

<%= form_tag('', method: 'post') do |f| %>
    <div class="form-group">
      <%= label 'Пин-код', :pincode %>
      <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
    </div>

    <div class="actions">
      <%= submit_tag %>
    </div>
<% end %>

<%= link_to 'На главную', events_path %>

app/views/events/show.html.erb
<div class="event">

  <div class="event-info row">

    <div class="col-md-12">
      <%# Выводим произвольную фотку в качестве фона для шапки события %>
      <%= content_tag 'div', '',
        class: 'event-background',
        style: "background-image: url(#{event_photo(@event)})"
      %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>
            <h3>
              <small>
                <%= @event.address %>
              </small>
            </h3>
            <p><%= @event.description %></p>
          </div>


          <% if current_user_can_edit?(@event) %>
            <div class="buffer-top">
              <%= link_to 'Изменить', edit_event_path(@event), class: 'btn btn-primary' %>
              <%= link_to 'Удалить', event_path, method: :delete,
                          data: {confirm: t('.destroy_event')}, class: 'btn btn-danger' %>
            </div>
          <% end %>
        </div>

        <div class="col-md-6">
          <div class="event-map" id="map" data-address="<%= @event.address %>"></div>
        </div>


      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="event-photos">
        <%# Выводим все фотографии события %>
        <div class="event-photos-gallery">
          <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
        </div>


        <%# Рисуем форму для добавления новой фотографии %>
        <div class="event-photo-form">
          <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
        </div>
      </div>

      <div class="event-comments buffer-top">

        <%= render partial: 'comments/form', locals: {comment: @new_comment || @event.comments.build} %>

        <div class="buffer-both">
          <%= render partial: 'comments/comment', collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="event-owner">
        <h4>Зовет:</h4>
        <p><%= render partial: 'users/user', object: @event.user %></p>
      </div>
      <div class="event-subscriptions">
        <h4>Пойдут:</h4>
        <div>
          <p>
            <%= render(
                    partial: 'subscriptions/subscription',
                    collection: @event.subscriptions.except(@new_subscription)
                ) %>
          </p>
        </div>
      </div>
      <% if current_user_can_subscribe?(@event) %>
        <div class="event-subscription-form">
          <h4>Я пойду:</h4>
          <div>
            <%= render partial: 'subscriptions/form', locals: {subscription: @new_subscription || @event.subscriptions.build} %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>